version: "3.8"
services:

    # PHP Service
    php:
        container_name: cp
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8002:8000
        depends_on:
            - database

    # Database Server
    database:
        container_name: db
        image: mysql:8.0
        ports:
            -   3308:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~
